version: 2

project_name: zipfuse

before:
  hooks:
    - make clean
    - make vendor
    - make lint
    - make test
    - make docs

builds:
  - id: zipfuse
    main: ./cmd/zipfuse
    binary: zipfuse
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    flags:
      - -trimpath
    ldflags:
      - -w
      - -s
      - -X main.Version={{.Version}}
      - -buildid=
    goos:
      - linux
    goarch:
    - amd64
    - arm
    - arm64
    - 386

  - id: mount.zipfuse
    main: ./cmd/mount.zipfuse
    binary: mount.zipfuse
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    flags:
      - -trimpath
    ldflags:
      - -w
      - -s
      - -X main.Version={{.Version}}
      - -buildid=
    goos:
      - linux
    goarch:
    - amd64
    - arm
    - arm64
    - 386

source:
  enabled: true

archives:
  -
    files:
      - LICENSE
      - INSTALL
      - docs/*.pdf
      - docs/*.text
      - src: "docs/*.1"
        dst: man
      - src: "docs/*.8"
        dst: man

signs:
  - artifacts: checksum

release:
  footer: |
    Most users will want the `linux_amd64` package (see installation instructions in `INSTALL`).  

    `.txz`, `.asc` and `.md5` files are part of the Slackware distribution package.  
    These specific packages are offered as a service for fellow Unraid OS enthusiasts.  

    Do note that any release files are unattended builds and served without any warranties.

