name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25.1
          cache: false
      - uses: actions/checkout@v4
      - name: golangci-lint migrate
        uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true
          version: latest
          args: migrate --timeout=5m
      - name: golangci-lint run
        uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true
          version: latest
          args: --timeout=5m
