name: golang-tests
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golang:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1
          cache: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean the environment
        run: make clean

      - name: Run all Go tests
        run: make test
