name: golang-build-debug
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golang:
    name: build-debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run all Go tests
        run: make test
      - name: Vendor the application for debug
        run: make vendor
      - name: Build the application for debug
        run: make debug
