name: zipfuse-docs
on:
  push:
    branches:
      - devel
  pull_request:
permissions:
  contents: read
jobs:
  zipfuse:
    name: docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Asciidoc
      run: |
        sudo apt-get update
        sudo apt-get install -y asciidoc

    - name: Build the documentation
      run: make docs
